version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: stocks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/stocks
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

  worker:
    build: ./worker
    container_name: worker
    restart: always
    depends_on:
      - backend
      - redis

  flower:
    build: ./flower
    container_name: flower
    restart: always
    depends_on:
      - worker
    ports:
      - "5555:5555"

volumes:
  postgres_data:
